services:
  postgres:
    image: postgres
    container_name: pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: olalekanrasaq1331
      POSTGRES_PASSWORD: Analyst@100
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: olalekanrasaq1331@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Analyst@10
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - pgnetwork
    depends_on:
      - postgres

  app:
    build: .
    container_name: py-app
    depends_on:
      - postgres
    networks:
      - pgnetwork
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "dbconnect.py", "dataqualitychecks.py", "generate-data-quality-report.py", "mytests.py"]  # Replace with your actual Python file

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  pgnetwork:
